# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "cocoapods", "~> 1.16"
gem "rexml", ">= 3.4.2"  # Fix for DoS vulnerability
gem "aws-sdk-s3", ">= 1.208.0"
gem "fastlane"